MovieShow/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieShow.Models;
using System.Diagnostics;

namespace MovieShow.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShow/ViewComponents/MovieViewComponent.cs
using MovieShow;
using Microsoft.AspNetCore.Mvc;
using MovieShow.Data;

namespace MovieShow.ViewComponents
{
    public class MovieViewComponent : ViewComponent
    {
        private AppDbContext db;
        public MovieViewComponent(AppDbContext _db)
        {
            db = _db;
        }
        public IViewComponentResult Invoke()
        {
            return View(db.Movies.OrderByDescending(x => x.MovieId).ToList());
        }
    }
}

MovieShow/ViewComponents/SerieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieShow;
using MovieShow.Data;

namespace MovieShow.ViewComponents
{

    public class SerieViewComponent : ViewComponent
    {
        private AppDbContext db;
        public SerieViewComponent(AppDbContext _db)
        {
            db = _db;
        }
        public IViewComponentResult Invoke()
        {
            var series = db.Series
                .Include(s => s.Season) // تحميل المواسم المرتبطة
                    .ThenInclude(season => season.Episode) // تحميل الحلقات المرتبطة
                .OrderByDescending(x => x.SerieId)
                .ToList();

            return View(series);
        }

    }
}

MovieShow/Views/Home/Index.cshtml
<div class="slider-section">
    <div class="slider">
        <div class="owl-carousel carousel carousel-nav-center" id="slide-carousel">
            <!-- slide item  -->
            <div class="slide-item">
                <img src="~/images/wanda-banner.jpg" alt="">
                <div class="overlay"></div>
                <div class="slide-item-content">
                    <div class="item-content-wrapper">
                        <div class="item-content item-content-title top-down">Wanda </div>
                        <div class="item-content-infos top-down delay-2">
                            <div class="item-content-info  rating">
                                <i class="bx bx-star flip-rtl"></i>
                                <span>9.6</span>
                            </div>
                            <div class="item-content-info time">
                                <i class="bx bx-time flip-rtl"></i>
                                <span>120 mins</span>
                            </div>
                            <div class="item-content-info resolution">
                                <i class='bx bx-tv flip-rtl'></i>
                                <span>hd</span>
                            </div>
                          
                        </div>
                        <div class="item-content-description top-down delay-4">
                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="slide-item">
                <img src="~/images/supergirl-banner.jpg" alt="">
                <div class="overlay"></div>
                <div class="slide-item-content">
                    <div class="item-content-wrapper">
                        <div class="item-content item-content-title top-down">super girl</div>
                        <div class="item-content-infos top-down delay-2">
                            <div class="item-content-info rating">
                                <i class="bx bx-star flip-rtl"></i>
                                <span>9.0</span>
                            </div>
                            <div class="item-content-info time">
                                <i class="bx bx-time flip-rtl"></i>
                                <span>90 mins</span>
                            </div>
                            <div class="item-content-info resolution">
                                <i class='bx bx-tv flip-rtl'></i>
                                <span>BluRay</span>
                            </div>
                   
                        </div>
                    </div>
                </div>
            </div>
            </div>
            </div>
            </div>
            <!-- end slide item  -->
@await Component.InvokeAsync("Movie")      
@await Component.InvokeAsync("Serie")